Lab2/Pages/Products/Detail.cshtml.cs
using Lab2.Business.IRepository;
using Lab2.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Lab2.Business.DTO;
using Lab2.Business.Services;
using System.Security.Cryptography;
using Newtonsoft.Json;

namespace Lab2.Pages.Products
{
    public class DetailModel : PageModel
    {
        string cart_name = "cart";
        IProductRepository _productRepository;
        private readonly CartService _cartService;
        public ProductDTO Product { get; set; } = default!;
        public int Pid { get; set; }

        public DetailModel(IProductRepository productRepository, CartService cartService)
        {
            _productRepository = productRepository;
            _cartService = cartService;
        }
        public void OnGet(int pid)
        {
            var product = _productRepository.getProductById(pid);
            Product = product;
            string message = TempData.Peek("message") as string;
        }

        public IActionResult OnPostAddToCart(int productId)
        {
            int quantity = Int32.Parse(Request.Form["quantity"]);
            ProductDTO p = _productRepository.getProductById(productId);

            // Get the current cart from the cookie
            List<CartItem> cart;
            string cartJson = Request.Cookies[cart_name];
            if (cartJson != null)
            {
                // Convert from Json to object
                cart = JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                cart = new List<CartItem>();
            }

            // Check if the cart item already exists in the cart
            CartItem existingCartItem = cart.FirstOrDefault(p => p.ProductItem.ProductId == productId);
            if (existingCartItem != null)
            {
                existingCartItem.Quantity += quantity;
            }
            else
            {
                ProductDTO product = new ProductDTO
                {
                    ProductId = p.ProductId,
                    ProductName = p.ProductName,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    QuantityPerUnit = p.QuantityPerUnit,
                    UnitPrice = p.UnitPrice,
                    UnitsInStock = p.UnitsInStock
                };

                CartItem newCartItem = new CartItem
                {
                    Quantity = quantity,
                    ProductItem = product
                };

                // add cart item to Cart
                cart.Add(newCartItem);
            }

            // config to skip property that cause infinite loop (ProductDTO reference -> CategoryDTO then CategoryDTO reference -> ProductDTO...)
            JsonSerializerSettings settings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            // Convert from object to Json
            string updatedCartJson = JsonConvert.SerializeObject(cart, settings);
            CookieOptions options = new CookieOptions
            {
                // only access by http or https, not Javascript
                HttpOnly = true,
                Expires = DateTime.Now.AddDays(7)
            };
            Response.Cookies.Append(cart_name, updatedCartJson, options);

            string message = "Add to cart successfully!";
            TempData["message"] = message;

            var returnUrl = Request.Headers["Referer"].ToString();
            return Redirect(returnUrl);
        }
    }
}

Lab2/Pages/Products/List.cshtml.cs
using Lab2.Business.IRepository;
using Lab2.Business.DTO;
using Lab2.DataAccess.Managers;
using Lab2.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Lab2.Pages.Products
{
    public class ListModel : PageModel
    {
        IProductRepository _productRepository;
        public List<ProductDTO> allProducts { get; set; }
        public List<ProductDTO> productsPaging { get; set; }
        public List<ProductDTO> productsGroupByCateID { get; set; }
        public List<ProductDTO> productsGroupBySupID { get; set; }
        public int SelectedCategoryId { get; set; }
        public int? CateID { get; set; }
        public int? SupID { get; set; }

       

        public int pageNo { get; set; }
        public int pageSize { get; set; }

        public int totalProducts { get; set; }

        public ListModel(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }


        private void GetData(int p, int s)
        {


        }

        public void onPost()
        {
           

        }

        public void OnGet(int p = 1, int s = 9, int? cateID = null, int? supID = null, string? price = null, string? search = "")
        {

            if (cateID.HasValue || supID.HasValue || !String.IsNullOrEmpty(price) || !String.IsNullOrEmpty(search))
            {
                productsPaging = _productRepository.searchProduct(p, s, (int?)supID, (int?)cateID, price, search);
                totalProducts = _productRepository.getTotalsearchProduct((int?)supID, (int?)cateID, price, search).Count;
                

            }


           

            if (!cateID.HasValue && !supID.HasValue && String.IsNullOrEmpty(price) && String.IsNullOrEmpty(search))
            {
                productsPaging = _productRepository.getListProduct(p, s);
                totalProducts = _productRepository.getListProduct().Count;
            }

            allProducts = _productRepository.getListProduct();



            pageSize = s;
            pageNo = p;
            productsGroupByCateID = _productRepository.getListProduct().GroupBy(item => item.CategoryId).Select(group => group.First()).ToList();
            productsGroupBySupID = _productRepository.getListProduct().GroupBy(item => item.SupplierId).Select(group => group.First()).ToList();

        }
    }
}

Lab2/Pages/Products/Detail.cshtml
@page
@model Lab2.Pages.Products.DetailModel
@using Lab2.DataAccess.Models
@using Lab2.Business.DTO
@{
    Layout = null;
}

@{
    ViewData["Title"] = "Detail";
}

<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    

</head>




<body>


    @{
        ProductDTO p = Model.Product;
        string message = TempData["message"] as string;
    }


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 " style="height:60px">
            <div class="container-fluid">

                <div class="row w-100 mt-3">

                    <div class="col-4">

                        <div class="row pt-1    ">
                            <a class="navbar-brand col-3" asp-area="" asp-page="">Food Store</a>

                            <div class="nav-item align-items-start col-2 mt-1 ">
                                <a class="nav-link text-dark " asp-area="" asp-page="/Products/List">
                                    <i class="fa-solid fa-house"></i>
                                </a>
                            </div>

                            <div class="col-3"></div>
                        </div>

                    </div>



                    <div class="col-5 ">
                    </div>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between col-3 align-items-end pt-2">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item mr-5" style="text-align:end">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
                                    <button class="btn btn-outline-secondary" type="button" id="button-addon2">

                                        <i class="fa-solid fa-magnifying-glass"></i>
                                    </button>
                                </div>
                            </li>

                            <li class="nav-item mt-1 px-3">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Carts/Cart">
                                    <i class="fa-solid fa-cart-shopping"></i>
                                </a>
                            </li>



                        </ul>
                    </div>

                </div>

            </div>
        </nav>
    </header>


    <div class="container-fluid">


        <div class="row d-flex flex-column">

            <h4 class="col-12 ">Product Detail</h4>

            <form method="post" asp-page-handler="AddToCart">
                <section class="col-12 mt-5">



                    <div class="row">

                        <div class="col-6">

                            <div class="row d-flex flex-column border border-primary rounded-1 mx-3 py-3 px-2 " style="width:500px">

                                <div class="col-6 w-100 mb-2">
                                    <input type="hidden" name="productId" value="@p.ProductId" />
                                </div>

                                <div class="col-6 w-100 mb-2">
                                    <div class=" row d-flex">

                                        <div class="col-6">
                                            Product Name:
                                        </div>

                                        <div class="col-4">
                                            @p.ProductName
                                        </div>

                                    </div>
                                </div>

                                <div class="col-6 w-100 mb-2">
                                    <div class=" row d-flex">

                                        <div class="col-6">
                                            Supplier:
                                        </div>

                                        <div class="col-4">
                                            @p.Supplier.CompanyName
                                        </div>

                                    </div>
                                </div>

                                <div class="col-6 w-100 mb-2">
                                    <div class=" row d-flex">

                                        <div class="col-6">
                                            Category:
                                        </div>

                                        <div class="col-4">
                                            @p.Category.CategoryName
                                        </div>

                                    </div>
                                </div>

                                <div class="col-6 w-100 mb-2">
                                    <div class=" row d-flex">

                                        <div class="col-6">
                                            Quantity per unit:
                                        </div>

                                        <div class="col-4">
                                            @p.QuantityPerUnit
                                        </div>

                                    </div>
                                </div>

                                <div class="col-6 w-100 mb-2">
                                    <div class=" row d-flex">

                                        <div class="col-6">
                                            Unit in stock:
                                        </div>

                                        <div class="col-4">
                                            @p.UnitsInStock
                                        </div>

                                    </div>
                                </div>

                                <div class="col-6 w-100 mb-2">
                                    <div class=" row d-flex">

                                        <div class="col-6">
                                            Unit in order:
                                        </div>

                                        <div class="col-4">
                                            @p.UnitsOnOrder
                                        </div>

                                    </div>
                                </div>

                                <div class="col-6 w-100 mb-2">
                                </div>





                            </div>



                        </div>

                        <div class="col-6">
                            <div class=" row d-flex flex-column">

                                <div class="col-6">
                                    <div class="row">
                                        <div class="col-3">
                                            Price:
                                        </div>
                                        <div class="col-4 px-5">
                                            @p.UnitPrice
                                        </div>
                                    </div>
                                </div>



                                <div class="row mt-2">

                                    <div class="col-2">
                                        Quantity:
                                    </div>

                                    @if (p.UnitsInStock < 1)
                                    {
                                        <div class="col-2 mb-5">
                                            <input type="number" min="0" max="@p.UnitsInStock" disabled />
                                        </div>

                                        <p class="text-danger">Out of stock</p>
                                    }
                                    else
                                    {


                                        <div class="col-2 mb-2">
                                            <input type="number" name="quantity" min="1" max="@p.UnitsInStock" />
                                        </div>

                                        <div class="col-8"></div>


                                        <div class="col-3">
                                            <button class="btn btn-primary mt-2" type="submit">Add to cart</button>
                                        </div>

                                        @if (!string.IsNullOrEmpty(message))
                                        {
                                            <div >
                                                <div>@message</div>
                                            </div>
                                        }



                                    }

                                </div>



                            </div>
                        </div>

                    </div>



                </section>
            </form>



        </div>



    </div>



</body>
</html>